DELETE FROM `U03vHM`.`appointment`;
DELETE FROM `U03vHM`.`customer`;
DELETE FROM `U03vHM`.`user`;
DELETE FROM `U03vHM`.`address`;
DELETE FROM `U03vHM`.`city`;
DELETE FROM `U03vHM`.`country`;

SET @t = ADDDATE(ADDDATE(TIMESTAMP(DATE(NOW()), TIME('09:56:12')), INTERVAL 1 MONTH), INTERVAL 1 WEEK);
SELECT @t;
