package scheduler.dao;

/**
 *
 * @author Leonard T. Erwine (Student ID 356334) &lt;lerwine@wgu.edu&gt;
 */
public enum ValidationResult {
    OK,
    ADDRESS_EMPTY, NO_CITY, CITY_NOT_SAVED, INVALID_CITY,
    NO_CUSTOMER, CUSTOMER_NOT_SAVED, CUSTOMER_INVALID,
    NO_USER, USER_NOT_SAVED, USER_INVALID, TITLE_EMPTY, NO_START_DATE, NO_END_DATE, START_FOLLOWS_END, URL_EMPTY, LOCATION_EMPTY, NAME_EMPTY,
    PASSWORD_EMPTY, DATA_OBJECT_DELETED, NO_COUNTRY, INVALID_COUNTRY, NO_ADDRESS, INVALID_ADDRESS, ADDRESS_NOT_SAVED, COUNTRY_NOT_SAVED;
}
